#Name network
network = "humans"

#Відсоток підписаних блоків валідатором
min_signed_per_window = 50

#Кількісь блоків з якого вирахоується дозволений відсоток пропуску
signed_blocks_window = 1200

#Час створення блоку в секундах
time_create_block = 5.5

#
rpc= [
    'http://65.108.228.178:16657'
    ]

#Шлях до бінарника
path_bin = "/path/to/humansd"

#Час для повторної перевірки
time_repeat = 1

#Кількість допущених блоків за цей час
missed_blocks = 8
